### ISSUE TITLE
Which .net core version will be in a next release of this template?

### ISSUE THREAD

**Issue by SychevIgor** [Azure/dotnet-template-azure-iot-edge-module#63]
Hello,
Template for a long enough time targeted .net core 2.1 (LTS https://dotnet.microsoft.com/platform/support/policy/dotnet-core). As I understand, template was not updated to .net core 2.2, because it was current release with 3 months support cycle).

In a branch I seen that .net core 3.0 version, but not merged in Master. 
![image](https://user-images.githubusercontent.com/578954/66206001-6b976b80-e6b7-11e9-94b7-c53afdcdc767.png)
As I know, .net core 3.0 it's also Current release, LTS will be 3.1 (planned on November 2019). 

Should we expect an update of template to 3.0 soon or you will wait 3.1 version of .net core later this year?

**Comment by SychevIgor** [comment]
Maybe you need a context of my question. I'm developing IoT Edge lab and for me it's a question- which version should I target. If soon will be .net core version of template- great, I can wait. otherwise I can continue with what we already have.

**Comment by davidzwa** [comment]
Interested as well, currently adjusting the template myself. Lot of work to do that each time, so a default template would be nice!

**Comment by blackchoey** [comment]
@SychevIgor @davidzwa The arm64-preview branch will be merged to master after Azure IoT Edge arm64 support reaches GA stage. At that time we will revisit whether to keep using .net core 3.0 or upgrade to newer version. 
If you don't have requirement to upgrade version of .net core, you can just use .net core 2.1. It's LTS version so have longer support period than .net core 3.0. IoT Edge doesn't limits the runtime of your module.

**Comment by fgheysels** [comment]
I've just created a new edge module in an existing IoT Edge solution, and it the new module is targetting .NET Core 3.1

Since each module runs as a container, theoretically it should not be a problem if I have certain modules running that target .NET Core 2.1 and others that target .NET Core 3.1, isn't it ?

Would it be considered best practice to align all modules to use the same .NET core version ?  Should we upgrade the system modules edgeHub & edgeAgent along ?

**Comment by blackchoey** [comment]
@fgheysels You don't need to align all modules to use the same .NET Core version. As you already mentioned, the module runs in a container so modules target different .NET Core version is not a problem.

**Comment by konichi3** [comment]
Obsolete issue. Sounds like the answer was provided. Feel free to open a new issue if that is not the case.
