### ISSUE TITLE
add support for project references/nuget feeds to docker build scripts

### ISSUE THREAD

**Issue by grahamehorner** [Azure/dotnet-template-azure-iot-edge-module#67]
the current templates create docker files which a developer may need to edit so the build is successful especially given the build fails when:-

1. a module project has a reference to share code/project in the solution;
           which is not in the module projects folder or subfolder. 

2. a nuget package is added from a feed other than nuget.org
           dotnet restore fails even if a nuget.config is present.

the template should direct a developer to resolution and/or suggest what is required to build module projects successfully when following these standard development practices or work oob with these approaches or provide addition tooling to support these usecases.

**Comment by blackchoey** [comment]
Hi @grahamehorner 
For 1), you can edit the `contextPath` in module.json file to the folder that contains both your module and reference project. The value of contextPath will be passed to docker command as build context when build.
For 2), Nuget CLI has command to add extra sources ([document](https://docs.microsoft.com/en-us/nuget/reference/cli-reference/cli-ref-sources)). You can use this command to add your own sources in docker file. The nuget inside docker won't read the nuget.config in your dev machine when restore.
We will consider add documents for the problems you met.

**Comment by blackchoey** [comment]
@grahamehorner We haven't hear from you for a while. I'm going to close this issue. If you have further questions, feel free to open new issues to discuss. Thanks.
