### ISSUE TITLE
Update image to MCR

### ISSUE THREAD

**Issue by adashen** [Azure/dotnet-template-azure-iot-edge-module#69]
https://github.com/microsoft/vscode-azure-iot-edge/issues/520

**Comment by blackchoey** [comment]
I will update the base image within next week.

**Comment by kiranpradeep** [comment]
1. Please see that in all iotedge github repo examples, the runtime is based on [alpine](https://github.com/Azure/iotedge/blob/master/edge-modules/TemperatureFilter/docker/linux/amd64/Dockerfile). Could the same be used in docker template?
2. Also all iotedge github repo examples are now based on [netcoreapp 3.0](https://github.com/Azure/iotedge/blob/master/edge-modules/TemperatureFilter/TemperatureFilter.csproj)? Could the same be used in csproj template?

**Comment by blackchoey** [comment]
@kiranpradeep Thanks for the details.
For 1), not all platforms have alpine based runtime images so we will keep using current image tags to make sure it works on all platforms. You can always change the base image after you created the project.

For 2) There is preview version of dotnet template that based on .net core 3.0. You can refer this blog [post](https://devblogs.microsoft.com/iotdev/develop-and-debug-arm64-iot-edge-modules-in-visual-studio-code-preview/) to try the preview version. For the stable version, I checked some docker images from IoT Edge (e.g. the SimulatedTemperatureSensor), they're still using .net core 2.1 so we will keep using .net core 2.1 in stable version for now. Of course, you can always change your project to use .net core 3.0 at anytime.

**Comment by blackchoey** [comment]
The template has been updated. Closing this issue.
