### ISSUE TITLE
Docker Build fails for arm32v7 after .net core 3.1 migration

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/dotnet-template-azure-iot-edge-module#77]
The templates are now migrating towards .Net 3.1.

I tried to compile the C# sample module for both amd64, arm32v7, and windows-amd64.

The Docker build works for both the amd64 and windows-amd64.

But the arm32v7 fails with this message:

    A fatal error occurred, the folder [/usr/share/dotnet/host/fxr] does not contain any version-numbered child folders
    The command '/bin/sh -c dotnet restore' returned a non-zero code: 131

![image](https://user-images.githubusercontent.com/694737/80139355-9e974300-85a6-11ea-81a9-96b8d0f98a68.png)

It seems this is an issue in the Docker file:

    https://github.com/Azure/dotnet-template-azure-iot-edge-module/blob/master/content/dotnet-template-azure-iot-edge-module/CSharp/Dockerfile.arm32v7

This seems to be related to https://github.com/dotnet/dotnet-docker/issues/1537 and https://github.com/microsoft/vscode-azure-iot-edge/issues/543

**Comment by blackchoey** [comment]
Hi @sandervandevelde The arm32v7 dockerfile uses arm32v7 base image on purpose to avoid following issue:
If the dockerfile uses images that work on multiple platform, building the arm32v7 dockerfile on an amd64 machine will only generate **amd64** image. This will cause unexpected errors when people think they get the arm32v7 image and try to run it on an arm32v7 machine.

Please refer the discussion in the issues you mentioned for more details.

**Comment by sandervandevelde** [comment]
Thanks. 

It feels like a breaking change regarding the previous docker file.

Please document this in the readme.

**Comment by ddobric** [comment]
Why is this issue closed? We still have the same issue when building for .net5 and .net6. Downloading applications to 3.1 seems to work well.

**Comment by konichi3** [comment]
@ddobric Happy new year! Could you please open a new issue so we can track your symptom accordingly? And when you create a new one, could you also share us the dockerfile you used to build .NET5 or .NET6 applications with additional information on your repro steps and your dev/target machine configurations?

**Comment by f2calv** [comment]
@ddobric the solution/workaround is here https://github.com/dotnet/dotnet-docker/issues/1537#issuecomment-755351628 :)

And here is my fully working demo multi-architecture repository https://github.com/f2calv/dotnet-multi-arch-container
